export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE'

export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_FAILURE = 'ADD_PRODUCT_FAILURE'

export const GET_PRODUCT = 'GET_PRODUCT'
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE'

export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const DELETE_SUCCESS = 'DELETE_SUCCESS'
export const DELETE_FAILURE = 'DELETE_FAILURE'

export const SEARCH_FILTER = 'SEARCH_FILTER'

export const GET_SEARCH = 'GET_SEARCH'
export const GET_SEARCH_SUCCESS = 'GET_SEARCH_SUCCESS'

export const GET_PRODUCT_DETAILS='GET_PRODUCT_DETAILS'
export const GET_PRODUCTS_DETAILS_SUCCESS = 'GET_PRODUCTS_DETAILS_SUCCESS'
export const GET_PRODUCTS__DETAILS_FAILURE = 'GET_PRODUCTS__DETAILS_FAILURE'